// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tequprzhtjockrwhhofc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlcXVwcnpodGpvY2tyd2hob2ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjM4NzEsImV4cCI6MjA2NTUzOTg3MX0.KWrJuFy0M5FCxyg8yTybuDNwoWEqZx8KsIv0oXryz-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);